# Validate our PRs follow the conventional commits spec
# See https://www.conventionalcommits.org/en/v1.0.0/#summary for details on the
# spec

name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          types: |
            fix
            feat
            perf 
            docs 
            wip
